#build Annotation level of Persons
#group keys from TEI statements

PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>

CONSTRUCT { 
    #kfngoei
	kfngoei:nnnn a kfngoeo:AnnoPerson ;
        rdfs:label "Annotation level of Persons"@en ;
        
        #key identifier for person
    	rdfs:isDefinedBy ?o_key ;

        #relation to target = the resource that is annotated
        kfngoeo:hasTarget kfngoei:nnnnnn;

        #relation to body = the annotation itself
        kfngoeo:hasBody kfngoei:nnnnnn ;
        .
}
WHERE {
    SELECT DISTINCT ?o_key
    WHERE {
        OPTIONAL {
            ?s rdf:type kfngoeo:StartTag ;
                  kfngoeo:elementName tei:persName ;
                  kfngoeo:hasAttr ?_bn ;
                  .
            ?_bn kfngoeo:attrName "key" ;
                 kfngoeo:attrValue ?o_key ;
            .                
        }   
        
    } GROUP BY ?o_key 
}