#build Annotation level of Index
#generate resource IDs for keys   

PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

#import: annoIndexi_1

CONSTRUCT {     
	?s_anno a kfngoeo:AnnoIndex ;
        rdfs:label "Annotation level of Index"@en ;        
    	rdfs:isDefinedBy ?o_key ;       
        kfngoeo:hasTarget ?_bn ;
        kfngoeo:hasBody kfngoei:nnnnnn ;
	.
}
WHERE {    
    ?s rdf:type kfngoeo:AnnoIndex ;
       rdfs:isDefinedBy ?o_key ;       
	.   
    BIND ( IF ( BOUND(?o_key), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_anno )
    BIND(IF(BOUND(?s_anno), BNODE(), ?nothing) AS ?_bn)
} ORDER BY ?o_key