PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
DELETE { 
    ?s_do a ldp:Container ;
          ?p_do ?o_do
    .
} 
WHERE { 
    ?s_do a ldp:Container ;
          ?p_do ?o_do
    .
}