PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

#import TB or MF

CONSTRUCT {
    ?s_anno a kfngoeo:AnnoDiv ;
        	rdfs:label "Annotation level of Div"@en ;                
    		rdfs:isDefinedBy ?key_div ;        
        	kfngoeo:hasTarget ?target_div ;
         	#no kfngoeo:hasBody
    .
}
WHERE {
    BIND(?s_div AS ?target_div)
    {
    	SELECT DISTINCT ?s_div ?key_div
        WHERE {
            ?s_tei a kfngoeo:StartTag ;
                    kfngoeo:elementName tei:TEI ;
                    kfngoeo:elementPos ?o_pos_tei ;
            .
            BIND(substr(?o_pos_tei,1,strlen(?o_pos_tei)-2) AS ?title_short)
            ?s_div a kfngoeo:StartTag ;
                    kfngoeo:elementName tei:div ;
                    kfngoeo:hasAttr [
                        kfngoeo:attrName ?o_name ;          		
                        kfngoeo:attrValue ?o_val_div ;
                    ] ;
                    kfngoeo:elementPos ?o_pos_div ;
            .            
            FILTER(?o_val_div = "diary-entry")            
            BIND(?o_val_div AS ?key_div)
        } GROUP BY ?s_div ?key_div
    }
    {
        SELECT DISTINCT ?s_div ?s_anno
        WHERE {
       		?s_div a kfngoeo:StartTag ;
            .
            BIND (IF(BOUND(?s_div), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_anno )
        }
    }
}