PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

#import TB or MF

CONSTRUCT {
    ?s_anno a kfngoeo:AnnoAdd ;
        	rdfs:label "Annotation level of Add"@en ;                
    		rdfs:isDefinedBy ?key_add ;        
        	kfngoeo:hasTarget ?target_add ;
         	#no kfngoeo:hasBody
    .
}
WHERE {
    ?s_tei a kfngoeo:StartTag ;
           kfngoeo:elementName tei:TEI ;
           kfngoeo:elementPos ?o_pos_tei ;
	.
    BIND(substr(?o_pos_tei,1,strlen(?o_pos_tei)-2) AS ?title_short)
    ?s_add a kfngoeo:StartTag ;
           kfngoeo:elementName tei:add ;                    
           kfngoeo:elementPos ?o_pos_add ;
	.
    BIND(?s_add AS ?target_add)
    BIND(?title_short AS ?key_add)
    BIND(IF(BOUND(?s_add), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing) AS ?s_anno)    
}