PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

#import TB or MF

CONSTRUCT {
    ?s_anno a kfngoeo:AnnoDate ;
        	rdfs:label "Annotation level of Date"@en ;                
    		rdfs:isDefinedBy ?key_date ;        
        	kfngoeo:hasTarget ?target_date ;
         	#no kfngoeo:hasBody
    .
}
WHERE {
    BIND(?s_date AS ?target_date)
    {
    	SELECT DISTINCT ?s_date ?key_date
        WHERE {
            ?s_tei a kfngoeo:StartTag ;
                    kfngoeo:elementName tei:TEI ;
                    kfngoeo:elementPos ?o_pos_tei ;
            .
            BIND(substr(?o_pos_tei,1,strlen(?o_pos_tei)-2) AS ?title_short)
            ?s_date a kfngoeo:StartTag ;
                    kfngoeo:elementName tei:date ;
                    kfngoeo:hasAttr [
                        kfngoeo:attrName ?o_name ;          		
                        kfngoeo:attrValue ?o_val_date ;
                    ] ;
                    kfngoeo:elementPos ?o_pos_date ;
            .
            BIND (IF( ?o_name = "from" || ?o_name = "to" || ?o_name = "when", ?o_val_date, ?nothing) AS ?o_val)
            FILTER(BOUND(?o_val))

            BIND(?o_val AS ?key_date)    
        } GROUP BY ?s_date ?key_date
    }
    {
        SELECT DISTINCT ?s_date ?s_anno
        WHERE {
       		?s_date a kfngoeo:StartTag ;
            .
            BIND (IF(BOUND(?s_date), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_anno )     
        }
    }
} ORDER BY ?key_date