#build Annotation level of Persons
#build bodies of annotations

PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
    ?s_anno a kfngoeo:AnnoPerson ;
        rdfs:label "Annotation level of Persons"@en ;
        
        #key identifier for person
    	rdfs:isDefinedBy ?o_key ;

        #relation to target = the resource that is annotated
        kfngoeo:hasTarget ?target_text ;

        #relation to body = the annotation itself
        kfngoeo:hasBody ?body_person ;
	.
}
WHERE {
    ?s_anno a kfngoeo:AnnoPerson ;
        rdfs:isDefinedBy ?o_key ;
        kfngoeo:hasTarget ?target_text ;
        kfngoeo:hasBody ?body ;
    .
	{
        SELECT DISTINCT ?o_key_person (?s_person AS ?body_person)
        WHERE {
            OPTIONAL {
                ?s_person a kfngoeo:Person ;
                    kfngoeo:identifier [
                        a kfngoeo:PropertyValue ;
                        kfngoeo:propertyID "CamelCase" ;
                        kfngoeo:value ?o_key_person ;
                    ] .                
            }
        }
	}    
    FILTER (?o_key = ?o_key_person)
}