#build Annotation level of Persons
#detect missing/wrong data in biographies

PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geonames: <http://www.geonames.org/ontology#>
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
PREFIX gnd: <http://d-nb.info/standards/elementset/gnd#>
PREFIX tei: <http://www.tei-c.org/ns/1.0>

SELECT DISTINCT ?o_key_text
WHERE {
    ?s_text rdf:type kfngoeo:StartTag ;
        kfngoeo:elementName tei:persName ;
        kfngoeo:hasAttr [
            kfngoeo:attrName "key" ;
            kfngoeo:attrValue ?o_key_text ;
        ]
    .    
	{
		SELECT (GROUP_CONCAT (?o_key_anno; separator = " ") AS ?result)
        WHERE { 
            ?s_anno a kfngoeo:AnnoPerson;
            rdfs:isDefinedBy ?o_key_anno ;
            .
        } 	
	}    
    filter (!contains(?result, ?o_key_text))		
}