PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

#import TB or MF, annoAnchorSpani, annoTextCompi_1-2

CONSTRUCT {
    ?s_anno a kfngoeo:AnnoAnchorApp ;
        	rdfs:label "Annotation level of Anchor for App"@en ;                
    		kfngoeo:hasTarget [
                kfngoeo:hasSource ?title_target ;
                kfngoeo:hasSelector [
                    a kfngoeo:TextPositionSelector ;
                    kfngoeo:start ?start_nr ;	#pos. of tei:addSpan
                    kfngoeo:end ?end_nr ;		#pos of tei:anchor
                ] 
        	] ;
         	#no kfngoeo:hasBody
    .
}
WHERE {
    ?s_anchor a kfngoeo:StartTag ;
           	kfngoeo:elementName tei:anchor ;		   
			kfngoeo:elementPos ?o_pos_anchor ;
 	.
    FILTER(!CONTAINS(?result, ?o_pos_anchor))    
    BIND(xsd:integer(SUBSTR(?o_pos_anchor,strlen(?title_short)+2)) AS ?start_nr)    
    BIND(?title_short AS ?title_target)
    ?s_textcomp a kfngoeo:AnnoTextComparison ;
  				kfngoeo:hasTarget [
        			kfngoeo:hasSource ?title_target ;
                    kfngoeo:hasSelector [
						a kfngoeo:TextPositionSelector ;                            
                        kfngoeo:start ?start_nr ;	#pos of tei:anchor                  
                        kfngoeo:end ?end_nr ;	#pos of tei:app
                    ]
                ] ;
	.
    {
        SELECT (GROUP_CONCAT (?o_pos_anchspan; separator = " ") AS ?result) ?title_short
        WHERE {
            ?s_tei a kfngoeo:StartTag ;
                    kfngoeo:elementName tei:TEI ;
                    kfngoeo:elementPos ?o_pos_tei ;
            .
            BIND(substr(?o_pos_tei,1,strlen(?o_pos_tei)-2) AS ?title_short)            
            ?s_annoanch a kfngoeo:AnnoAnchorSpan ;
                    kfngoeo:hasTarget [                        
                        kfngoeo:hasSelector [
                            a kfngoeo:TextPositionSelector ;                            
                            kfngoeo:end ?end_nr ;	#pos of tei:anchor
                        ] 
                    ] ;                    
            .
            BIND(concat(?title_short, '_', str(?end_nr)) AS ?o_pos_anchspan)
            ?s_anchspan a kfngoeo:StartTag ;
						kfngoeo:elementName tei:anchor ;						
						kfngoeo:elementPos ?o_pos_anchspan ;
 			.
        } GROUP BY ?title_short
    }
    {
        SELECT DISTINCT ?s_anchor ?s_anno
        WHERE {
       		?s_anchor a kfngoeo:StartTag ;
            .
            BIND (IF(BOUND(?s_anchor), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_anno )     
        }
    }
}