PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

#import Text files

CONSTRUCT {
    ?s_anno 	
        a ?type_anno ;
		rdfs:label ?label_anno ;                
		rdfs:isDefinedBy ?key ;        
        kfngoeo:hasTarget 
            [
            kfngoeo:hasSource ?title_target ;
            kfngoeo:hasSelector [
                a kfngoeo:TextPositionSelector ;
                kfngoeo:start ?start_nr_target ;
            	kfngoeo:end ?end_nr_target ;
            ] 
        ] ;
		kfngoeo:hasBody [        
            a kfngoeo:TextualBody;
            kfngoeo:hasSource ?title_body ; 
            kfngoeo:hasSelector ?start_nr_body ;	#start nr of body            
        ] ; 
    .
}
#SELECT ?o_key_val ?o_el ?type_anno
WHERE {    
    {
        SELECT DISTINCT ?o_key_val ?o_el ?type_anno
    	WHERE {            
            ?s_reg a kfngoeo:StartTag ;
				kfngoeo:elementName ?o_el ;
                kfngoeo:hasAttr [
                	kfngoeo:attrName "key" ;
                    kfngoeo:attrValue ?o_key_val ;
                ] ;                
     		.
			FILTER(?o_el = tei:persName || ?o_el = tei:placeName || ?o_el = tei:orgName || ?o_el = tei:index)
            OPTIONAL{BIND(IF(?o_el = tei:orgName, kfngoeo:AnnoOrg, ?nothing) AS ?type_anno)}
    	} GROUP BY ?o_key_val ?o_key ?o_el ?type_anno
        ORDER BY ?o_key_val
    }
    #BIND (IF(BOUND(?o_key_person), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing) AS ?s_anno)
       
} #LIMIT 10