#build Annotation level of Persons
#build bodies of annotations

PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geonames: <http://www.geonames.org/ontology#>
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
PREFIX gnd: <http://d-nb.info/standards/elementset/gnd#>
PREFIX tei: <http://www.tei-c.org/ns/1.0>

CONSTRUCT {
    ?s_anno a kfngoeo:AnnoPerson ;
        rdfs:label "Annotation level of Persons"@en ;
        
        #key identifier for person
    	rdfs:isDefinedBy ?o_key ;

        #relation to target = the resource that is annotated
        kfngoeo:hasTarget ?target_text ;

        #relation to body = the annotation itself
        kfngoeo:hasBody ?body_person ;
	.
}
WHERE {
    ?s_anno rdf:type kfngoeo:AnnoPerson ;
        rdfs:isDefinedBy ?o_key ;
        kfngoeo:hasTarget ?target_text ;
        kfngoeo:hasBody ?body ;
    .                            
    
	{
		SELECT DISTINCT ?o_key_person (?s_person AS ?body_person)
        WHERE {
            OPTIONAL {
                ?s_person rdf:type kfngoeo:Person ;
                    kfngoeo:identifier [
                        a kfngoeo:PropertyValue ;
                        kfngoeo:propertyID "CamelCase" ;
                        kfngoeo:value ?o_key_person ;
                    ] .                
            }
        }
	}    
    FILTER (?o_key = ?o_key_person)
}
	
    

