#build Annotation level of Persons
#generate resource IDs for grouped keys   

PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT { 
    #kfngoei
	$this a kfngoeo:AnnoPerson ;
        rdfs:label "Annotation level of Persons"@en ;
        
        #key identifier for person
    	rdfs:isDefinedBy ?o_key ;

        #relation to target = the resource that is annotated
        kfngoeo:hasTarget kfngoei:nnnnnn ;

        #relation to body = the annotation itself
        kfngoeo:hasBody kfngoei:nnnnnn ;
	.
}
WHERE {
    {
		SELECT DISTINCT ?o_key (?s_anno AS $this)
        WHERE {
            OPTIONAL {
                ?s rdf:type kfngoeo:AnnoPerson ;
                      rdfs:isDefinedBy ?o_key ;
				.                            
            }    
            BIND ( IF ( BOUND(?o_key), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_anno )
        } GROUP BY ?o_key ?s_anno        
    }    
}
