PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
delete{
    ?s_anno a kfngoeo:AnnoPerson ;
         	kfngoeo:hasBody kfngoei:nnnnnn ;
        	?p ?o ;
    .    
}
where { 
	?s_anno a kfngoeo:AnnoPerson ;
         	kfngoeo:hasBody kfngoei:nnnnnn ;
        	?p ?o ;
    .
}