#Connect do to text
PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ldp: <http://www.w3.org/ns/ldp#>
CONSTRUCT {
	?s_do ?p_do ?o_do ;
        ldp:contains ?o_s_text ;       
       .
}
WHERE {
    ?s_text a kfngoeo:StartTag ;
            kfngoeo:elementName tei:TEI ;
            kfngoeo:elementPos ?pos ;            
    .    
    ?s_do a ldp:Container ;
          ?p ?o ;
          dcterms:title ?title_short ;
    .
    BIND (  IF ( ?p = ldp:contains, ?nothing, ?p) AS ?p_do)
    BIND (  ?o AS ?o_do)    
    BIND (  IF ( STRSTARTS(?pos, ?title_short), ?s_text, ?nothing) AS ?o_s_text)    
}