PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
    ?s_main
        a kfngoeo:Text_main ;
        kfngoeo:hasContent ?o_main ;
        kfngoeo:elementPos rdf:nnnn ;
    .
    ?s_sub
        a kfngoeo:Text_sub ;
        kfngoeo:hasContent ?o_sub ;
        kfngoeo:elementPos rdf:nnnn ;
	.
}
WHERE {     
    {
     	SELECT ?s_main ?o_main
        WHERE {
            kfngoei:n3 a kfngoeo:Text_main ;
                    kfngoeo:hasContent ?o_main ;
                    .
            BIND ( IF ( BOUND(?o_main), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_main )
        }
    }
    {
        SELECT ?s_sub ?o_sub
        WHERE {
            kfngoei:n6 a kfngoeo:Text_sub ;
                    kfngoeo:hasContent ?o_sub ;
                    .
            BIND ( IF ( BOUND(?o_sub), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_sub )
        }
    }
} ORDER BY ?o_main ?o_sub
#LIMIT 4 