PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

#SELECT ?s_main ?s_sub ?term_main ?term_sub
CONSTRUCT {
    #kfngoei:n3
    ?s_main
        a kfngoeo:Text ;
        kfngoeo:hasContent ?term_main ;
        kfngoeo:elementPos rdf:nnnn ;
    .
    #kfngoei:n6
    ?s_sub
        a kfngoeo:Text ;
        kfngoeo:hasContent ?term_sub ;
        kfngoeo:elementPos rdf:nnnn ;
    .
}
WHERE { 
    {
    	SELECT ?s_main ?term_main
        WHERE {
            kfngoei:n3 a kfngoeo:Text ;
                    kfngoeo:hasContent ?term_main ;
                    .
            BIND ( IF ( BOUND(?term_main), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_main )
        }    
    } .
    {
    	SELECT ?s_sub ?term_sub
        WHERE {
            kfngoei:n6 a kfngoeo:Text ;
                kfngoeo:hasContent ?term_sub ;
                .
            BIND ( IF ( BOUND(?term_sub), URI(CONCAT("https://github.com/KfNGOe/kfngoei/", STRUUID())), ?nothing ) AS ?s_sub )
        }    
    }
     
        
} ORDER BY ?term_main ?term_sub
#limit 3 
