PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>

SELECT DISTINCT ?o_attr 
WHERE { 
	?s_name kfngoeo:hasAttr [
        kfngoeo:attrName ?o_attr ;
	]
    .
} ORDER BY ?o_attr