#build Annotation level of Persons
#detect missing/wrong data in biographies

PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
SELECT DISTINCT (?s_person AS ?localID) ?entry_person ?gender ?birth ?death ?bio ?pid
WHERE {
    ?s_anno a kfngoeo:AnnoPerson ;            
            kfngoeo:hasBody ?s_person ;
    .
    ?s_person a kfngoeo:Person ;			
            kfngoeo:gender ?gender ;
            kfngoeo:preferredNameEntityForThePerson [
            	a kfngoeo:NameOfThePerson ;
            	kfngoeo:preferredNameForThePerson ?entry_person ;                
            ] ;
            kfngoeo:dateOfBirth ?birth ;
            kfngoeo:dateOfDeath ?death ;
            kfngoeo:biographicalOrHistoricalInformation ?bio ;
            kfngoeo:identifier [
        		a kfngoeo:PropertyValue ;
				kfngoeo:propertyID "GND" ;
				kfngoeo:value ?pid ;
    		]              
	.
}
ORDER BY ?entry_person