PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

#import: register

SELECT (?o_pos_item AS ?id) (?o_text AS ?key)
WHERE {
    ?s_tei kfngoeo:elementName tei:TEI ;
           kfngoeo:elementPos ?o_pos_tei ;
 	.
    BIND(substr(?o_pos_tei,1,strlen(?o_pos_tei)-1) AS ?title_short)    
    ?s_item
        a kfngoeo:StartTag ;
        kfngoeo:elementName tei:item ;
        kfngoeo:elementPos ?o_pos_item ;
	.
    FILTER(CONTAINS(?o_pos_item, ?title_short))            
    BIND(xsd:integer(substr(?o_pos_item,strlen(?title_short)+1)) AS ?o_pos_item_nr)
    BIND(concat(?title_short, str(?o_pos_item_nr+1)) AS ?o_pos_term)    
    OPTIONAL {
        ?s_term_main 
            a kfngoeo:StartTag ;
            kfngoeo:elementName tei:term ;
            kfngoeo:hasAttr [
                kfngoeo:attrName "type" ;
                kfngoeo:attrValue "main" ;
            ] ;			
            kfngoeo:elementPos ?o_pos_term ;
        .
    }
    OPTIONAL {
        ?s_term_key 
            a kfngoeo:StartTag ;
            kfngoeo:elementName tei:term ;
            kfngoeo:hasAttr [
                kfngoeo:attrName "type" ;
                kfngoeo:attrValue "key" ;
            ] ;			
            kfngoeo:elementPos ?o_pos_term ;
        .
    }
    BIND(xsd:integer(substr(?o_pos_term,strlen(?title_short)+1)) AS ?o_pos_term_nr)
    BIND(concat(?title_short, str(?o_pos_term_nr+1)) AS ?o_pos_text)
    	?s_text 
        	a kfngoeo:Text ;
			kfngoeo:hasContent ?o_text ;
			kfngoeo:elementPos ?o_pos_text ;
 		.    	
}