PREFIX xml: <http://www.w3.org/XML/1998/namespace/>
PREFIX kfngoeo: <https://github.com/KfNGOe/kfngoeo#>
PREFIX tei: <http://www.tei-c.org/ns/1.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX kfngoei: <https://github.com/KfNGOe/kfngoei/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?o_content
#SELECT ?o_tag ?o_elname ?o_attrname ?o_attrval ?o_xmlid ?o_pos ?o_content
WHERE {
    ?s_tei a kfngoeo:StartTag ;
           kfngoeo:elementName tei:TEI ;
           kfngoeo:elementPos ?o_pos_tei ;
	.
    BIND(substr(?o_pos_tei,1,strlen(?o_pos_tei)-2) AS ?title_short)
    ?s_text a kfngoeo:StartTag ;
       kfngoeo:elementName tei:text ;
       kfngoeo:elementPos ?o_pos_text ;
	.
    BIND(xsd:integer(substr(?o_pos_text,strlen(?title_short)+2)) AS ?o_pos_text_nr)
    ?s_tag a ?o_tag ;
       kfngoeo:elementName ?o_elname ;
       kfngoeo:hasAttr ?_bn1 ;
       kfngoeo:hasAttr [        
        kfngoeo:attrName "xml:id" ;
        kfngoeo:attrValue ?o_xmlid ;
       ] ;
       kfngoeo:elementPos ?o_pos ;
	.
    OPTIONAL{
    	?_bn1 kfngoeo:attrName ?o_attrname ;
          kfngoeo:attrValue ?o_attrval ;
		.
    	FILTER(?o_attrname != "xml:id")    
    }    
    BIND(xsd:integer(substr(?o_pos,strlen(?title_short)+2)) AS ?o_pos_nr)    
    FILTER(?o_pos_nr > ?o_pos_text_nr)
    FILTER(?o_elname != tei:app && ?o_elname != tei:rdg && ?o_elname != tei:note && ?o_elname != tei:del)
    BIND(concat(?title_short, '_', str(?o_pos_nr+1)) AS ?o_pos_content)    
    OPTIONAL{
    	?s a ?o ;        
           ?p ?o_content_test ;
       	   kfngoeo:elementPos ?o_pos_content ;
		.
        FILTER(?p != rdf:type)    
        FILTER(?o = kfngoeo:Text && ?p = kfngoeo:hasContent)        
    }
    BIND(concat(?title_short, '_', str(?o_pos_nr+3)) AS ?o_pos_index)
    OPTIONAL{
        ?s_index a ?o_index ;
                 ?p_index ?o_el_index ; #?p_index = a, elementName, hasAttr, elementPos
                 kfngoeo:elementPos ?o_pos_index ;
		.
        FILTER(?p_index != rdf:type && ?p_index != kfngoeo:hasAttr && ?p_index != kfngoeo:elementPos)    
        BIND ( IF (?o_index = kfngoeo:EndTag && ?o_el_index = tei:index, ?nothing, ?o_content_test) AS ?o_content)
    }
}