name: Build project test

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:

jobs:
  setup_graphdb:
    name: Setup GraphDB
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Install dependencies
        run: |
          set -e
          sudo bash install.sh
      - name: Start GraphDB
        run: |
          set -e
          nohup sudo bash gdb_start.sh &
      - name: Wait for GraphDB
        run: |
          set -e
          sudo bash gdb_ping.sh
        shell: bash

  build_texts:
    name: Build texts
    runs-on: ubuntu-latest
    needs: setup_graphdb
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v3      
      - name: Create repo in GraphDB
        run: sudo bash gdb_createRepo.sh
      - name: Get repo list
        run: sudo bash gdb_getRepo.sh
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: .

  build_register:
    name: Build register
    runs-on: ubuntu-latest
    needs: [setup_graphdb, build_texts]
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files      
      - name: Start graphdb
        run: sudo bash gdb_start.sh &
      - name: Wait for graphdb
        run: sudo bash gdb_ping.sh
        shell: bash
      - name: Create repo
        run: sudo bash gdb_createRepo.sh
      - name: Get repo list
        run: sudo bash gdb_getRepo.sh
    

