name: Build project
on:
  #push:
  #  paths:      
  #    - "data/ttl/text/**"
  #    - "data/xlsx/**"
  #    - "html/data/img/**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_pages:    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: rm data
        run: |
          rm -rf data/tei_xmlId/*
          cp -r data/tei/text/Bae_MF_6-1.xml data/tei_xmlId/
      - name: Deploy tei with xmlid to data repo
        run: |
          git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/rh1967/dev-baernreither-data.git          
          mkdir -p dev-baernreither-data/data/tei/tei_built          
          if [ -d "data/tei_xmlId" ]; then cp -r data/tei_xmlId/* dev-baernreither-data/data/tei/tei_built/; fi
          cd dev-baernreither-data
          git config --global user.email "dev-baernreither-data@github.io"
          git config --global user.name "rh1967"
          git status
          git add ./data/tei/tei_built
          git commit -am "Deploy data to data repo" || echo "No changes to commit"
          git push https://${{ secrets.ACCESS_TOKEN }}@github.com/rh1967/dev-baernreither-data.git main
      - name: Push Results Back to Source Repo
        run: |
          git config --global user.email "dev-baernreither-app@github.io"
          git config --global user.name "rh1967"
          git status          
          git add html/*.html
          git commit -m "Deploy data back to app repo" || echo "No changes to commit"
          git push


#- name: Setup pages
#  uses: actions/configure-pages@v5
#- name: Upload artifact
#  uses: actions/upload-pages-artifact@v3
#  with:
#   #Upload html directory
#   path: './html'
#- name: Deploy to GitHub Pages
#  id: deployment
#  uses: actions/deploy-pages@v4