name: Build project
on:
  #push:
  #  paths:      
  #    - "data/ttl/text/**"
  #    - "data/xlsx/**"
  #    - "html/data/img/**"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_pages:    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Push Results Back to Source Repo
        run: |
          git config --global user.email "dev-baernreither-app@github.io"
          git config --global user.name "rh1967"          
          git add .
          git commit -m "Automated update: Adding results from workflow" || echo "No changes to commit"
          git push origin main